name: Test Coverage

on:
    pull_request:
    push:

permissions:
    contents: read
    actions: read
    checks: write

env:
    tools: composer:v2
    cache-version: 1

jobs:
    coverage:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php-version: [ '8.3', '8.4', '8.5' ]

        name: Test Coverage - PHP ${{ matrix.php-version }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: pcov
                    tools: ${{ env.tools }}

            -   name: Setup problem matchers for PHP
                run: 'echo ::add-matcher::${{ runner.tool_cache }}/php.json'

            -   name: Get Composer cache directory
                id: composercache
                run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

            -   name: Cache PHP dependencies
                uses: actions/cache@v5
                with:
                    path: ${{ steps.composercache.outputs.dir }}
                    key: ${{ runner.os }}-php${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-php${{ matrix.php-version }}-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

            -   name: Run Tests with coverage
                run: composer test-coverage

            -   name: Test Report
                uses: dorny/test-reporter@v3
                with:
                    name: TESTER Tests
                    path: tests/reports/junit.xml
                    reporter: tester-junit

            -   name: Upload tests results report to Codecov
                uses: codecov/codecov-action@v6
                if: ${{ matrix.php-version == '8.5' }}
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: tests/reports/junit.xml
                    fail_ci_if_error: true
                    report_type: test_results

            -   name: Upload tests coverage report to Codecov
                uses: codecov/codecov-action@v6
                if: ${{ matrix.php-version == '8.5' }}
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: tests/reports/coverage.xml
                    fail_ci_if_error: true
                    report_type: coverage

